### ISSUE TITLE
Importing anything the player sits on from Fallout 4 causes ValueError: 0 is not a valid FurnAnimationType.

### ISSUE THREAD

**Issue by 6ooflames** [BadDogSkyrim/PyNifly#114]

**Comment by 6ooflames** [comment]
´Import of nif failed
Traceback (most recent call last):
  File "C:\users\david\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_nifly\__init__.py", line 1329, in execute
    NifImporter.do_import(self.filepath, flags)
  File "C:\users\david\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_nifly\__init__.py", line 1285, in do_import
    imp.execute()
  File "C:\users\david\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_nifly\__init__.py", line 1267, in execute
    objs = self.import_extra(self.nif)
  File "C:\users\david\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\io_scene_nifly\__init__.py", line 716, in import_extra
    obj['AnimationType'] = FurnAnimationType(fm.animation_type).name
  File "Z:\home\david\Applications\blender-3.1.2-windows-x64\3.1\python\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "Z:\home\david\Applications\blender-3.1.2-windows-x64\3.1\python\lib\enum.py", line 710, in __new__
    raise ve_exc
ValueError: 0 is not a valid FurnAnimationType
Traceback (most recent call last):
  File "<blender_console>", line 7, in <module>
  File "Z:\home\david\Applications\blender-3.1.2-windows-x64\3.1\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)´

**Comment by 6ooflames** [comment]
Now it also accurse with other NpcChair and NpcCouch ids...
Any ideas how to get around this/quick&dirty fix?
If you point me at the right part of code, I'll fix it myself.

**Comment by 6ooflames** [comment]
Thanks so much!

**Comment by 6ooflames** [comment]
It just works.

**Comment by 6ooflames** [comment]
But the bug persists if I try importig batches with nifs with that script I made.
I would have to filter every npcchair/couch/ect... to get good results for my grade...
It would be nice to have a way to still import with missing data.
The textures and materials don't work right anyway...
K thanks for not closing it yet.
David

**Comment by BadDogSkyrim** [comment]
Yeah, I'll fix the underlying problem. 

I think it happens because the way I translate flags into user-visible strings doesn't deal with unexpected input and it should. Plus it should import the FO4 furniture markers.

**Comment by 6ooflames** [comment]
Yeah that would be an awesome solution for my usecase, thx.

**Comment by BadDogSkyrim** [comment]
V5.4, just for you.

**Comment by 6ooflames** [comment]
Awesome dude.
