### ISSUE TITLE
cannot import nif; using 2.8.0 and blender 3.4.1

### ISSUE THREAD

**Issue by freeaim** [BadDogSkyrim/PyNifly#141]
title
nif is resaved on nifskope

`PYNIFLY IMPORT NIF V8.2.0`

INFO:pynifly:Importing FO4 file D:\Desktop\fo4 modding tools\Warfighter The Ultimate M4 Pack 2.0\Meshes\warfightersworkshop\wzxm4\bodym16.nif
WARNING:pynifly:'NoneType' object has no attribute 'inputs'
ERROR:pynifly:Import of nif failed
Traceback (most recent call last):
  File "C:\Users\sonic\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_nifly\__init__.py", line 1963, in execute
    NifImporter.do_import(fullfiles, flags)
  File "C:\Users\sonic\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_nifly\__init__.py", line 1883, in do_import
    imp.execute()
  File "C:\Users\sonic\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_nifly\__init__.py", line 1859, in execute
    self.import_nif()
  File "C:\Users\sonic\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_nifly\__init__.py", line 1701, in import_nif
    self.import_shape(s)
  File "C:\Users\sonic\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_nifly\__init__.py", line 1138, in import_shape
    obj_create_material(new_object, the_shape)
  File "C:\Users\sonic\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_scene_nifly\__init__.py", line 463, in obj_create_material
    txtnode.location = (bdsf.location[0] + img_offset_x, bdsf.location[1])
AttributeError: 'NoneType' object has no attribute 'location'
INFO:pynifly:

`PyNifly IMPORT of ['bodym16.nif'] completed WITH ERRORS {'CANCELLED'}`
[bodym16.zip](https://github.com/BadDogSkyrim/PyNifly/files/11026956/bodym16.zip)

**Comment by podvornyakva** [comment]
Blender 3.3.2. Pynifly 8.2. Import successful.

**Comment by BadDogSkyrim** [comment]
Looks like the Blender team is playing with shaders again.

**Comment by podvornyakva** [comment]
They make it all the time. Soon will come out 3.5. And definitely they brake compatibility again. Major releases adds and remove features and, what  is more important, change DATA STRUCTURE. Do not waste tame. Focus on 3.3 LTS compatibility. Once another LTS is come out - than it be reasonable.
We say "what do you need: checkers or drive?" I prefer "drive" instead of bleeding edge Blender.

**Comment by BadDogSkyrim** [comment]
Looks like 3.5 is out now, so I'll upgrade to that. I like to keep up with the latest version as I can.

**Comment by BadDogSkyrim** [comment]
3.5 supported in latest release.
