### ISSUE TITLE
Can't import any HKX (12.1.0)

### ISSUE THREAD

**Issue by TokyoSU** [BadDogSkyrim/PyNifly#171]
Seem like i can't import skeleton nor animation nor any HKX (like DeathclawProject.hkx or skeleton.hkx or DeathclawEverything.hkx or DeathclawRootBehavior.hkx)
It always fail at creating the xml, i even started blender in admin just in case it was permission but nothing.
![Fallout4ImportHKX](https://github.com/BadDogSkyrim/PyNifly/assets/77746747/38082752-077e-45df-b265-58e65371db3b)
Through the nif work :)
![Fallout4Nif](https://github.com/BadDogSkyrim/PyNifly/assets/77746747/ff8d57c5-b681-48aa-8af6-7b67f0ad15f2)
Using latest blender 3.6.
A tutorial about how to use this tools would be great 👍

**Comment by BadDogSkyrim** [comment]
This is only working for Skyrim LE. I'm hunting a solution for FO4.

**Comment by TokyoSU** [comment]
So i switched to Skyrim LE, it's working :)

**Comment by podvornyakva** [comment]
> hunting

Hey, Man! I get same issue. I'm sitting on Skyrim AE. Made all along your youtube tutorial and get this.

====================================
PYNIFLY IMPORT HKX V12.4.0

ERROR:pynifly:Import of HKX file failed
Traceback (most recent call last):
  File "Z:\media\box\data\projects\model\software\3.6.5-windows\3.6\scripts\addons\io_scene_nifly\__init__.py", line 2777, in execute
    self.xmlfile = xmltools.XMLFile(self.filepath, self)
  File "Z:\media\box\data\projects\model\software\3.6.5-windows\3.6\scripts\addons\io_scene_nifly\xmltools.py", line 36, in __init__
    self.open(filepath)
  File "Z:\media\box\data\projects\model\software\3.6.5-windows\3.6\scripts\addons\io_scene_nifly\xmltools.py", line 115, in open
    fp = XMLFile.hkx_to_xml(self.hkx_filepath)
  File "Z:\media\box\data\projects\model\software\3.6.5-windows\3.6\scripts\addons\io_scene_nifly\xmltools.py", line 62, in hkx_to_xml
    raise RuntimeError(f"Failed to create {xml_filepath}")
RuntimeError: Failed to create C:\users\steamuser\Temp\tmp_stf_equip.xml
INFO:pynifly:

PyNifly IMPORT of stf_equip.hkx completed WITH ERRORS
====================================
xmltools.py

        if not os.path.exists(hkx_filepath):
            raise ValueError(f"Failed to create {hkx_filepath}")

Got three files in pointed folder: 3388_autosave.blend,  tmp_stf_equip.hkx, tmp_stf_equip_1.hkx.
But no xml.

**Comment by BadDogSkyrim** [comment]
Doesn't work on AE or SE. LE only. The HKX is different.

**Comment by podvornyakva** [comment]
It is very disappointing... :(
Isnt Fallout 4 HKX different either?

**Comment by podvornyakva** [comment]
> Doesn't work

By the way. There is hkxconv project on git hub. My buddy tested it for me on Windows platform and it works for SE/AE. It uses HKX2Library. Same - project on Git hub in source code. Pity that i can't run it on Linux WINE. Anyway - HKX2Library is solution.

**Comment by jjtnb123** [comment]
Is your problem solved? I'm also having the same issue

**Comment by jjtnb123** [comment]
![30b8e489-5b13-4bda-bfa5-327cf8d58dcb](https://github.com/user-attachments/assets/7f7df54c-e310-4cbf-b356-bf1fa1b2ce82)
