### ISSUE TITLE
cannot activate addon on mac

### ISSUE THREAD

**Issue by core36** [BadDogSkyrim/PyNifly#214]
uppon trying to activate the addon in blender 4.1.1 on my m1 mac, this is the error i receved:

```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender.app/Contents/Resources/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/florian/Library/Application Support/Blender/4.1/scripts/addons/io_scene_nifly/__init__.py", line 77, in <module>
    from blender_defs import *
  File "/Users/florian/Library/Application Support/Blender/4.1/scripts/addons/io_scene_nifly/blender_defs.py", line 17, in <module>
    _GetShortPathNameW = ctypes.windll.kernel32.GetShortPathNameW
                         ^^^^^^^^^^^^^
AttributeError: module 'ctypes' has no attribute 'windll'
```

i have not tested it on any other OS, but from the name "windll" i suspect this error might limit the plugin to be windows only

**Comment by Anqui3tas** [comment]
same here, cannot install on Mac.

**Comment by BadDogSkyrim** [comment]
Sorry, windows only. Depends on a DLL that does the nif access.

**Comment by core36** [comment]
> Sorry, windows only. Depends on a DLL that does the nif access.

too bad. if the stars align and for some magical reason i fix this on my own, i'll come back here and share my findings
