### ISSUE TITLE
TypeError: can only concatenate str (not "int") to str

### ISSUE THREAD

**Issue by praecipitator** [BadDogSkyrim/PyNifly#221]
```
ERROR:pynifly:Export of nif failed
Traceback (most recent call last):
  File "<snip>\Blender Foundation\Blender\4.1\scripts\addons\io_scene_nifly\__init__.py", line 5275, in execute
    if targ.parent:
        ^^^^^^^^^^^^
  File "<snip>\Blender Foundation\Blender\4.1\scripts\addons\io_scene_nifly\__init__.py", line 5052, in export
    if context.object.mode != 'OBJECT':
    ^^^^^^^^^^^^^^
  File "<snip>\Blender Foundation\Blender\4.1\scripts\addons\io_scene_nifly\__init__.py", line 5039, in execute
    if obj and 'PYN_EXPORT_POSE' in obj:
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<snip>\Blender Foundation\Blender\4.1\scripts\addons\io_scene_nifly\__init__.py", line 4990, in export_file_set
    def __init__(self):

  File "<snip>\Blender Foundation\Blender\4.1\scripts\addons\io_scene_nifly\__init__.py", line 4821, in export_shape
    elif (not suffix) and self.facebones:
                                 ^^^^^^^^^
  File "<snip>\Blender Foundation\Blender\4.1\scripts\addons\io_scene_nifly\__init__.py", line 3626, in unique_name
    elif obj.type == 'EMPTY':
            ^^^^^^^^^^^^^^^^^^
TypeError: can only concatenate str (not "int") to str
INFO:pynifly:

PyNifly EXPORT of {'praTEMP_PACage:ROOT'} completed WITH ERRORS
====================================
```
This was caused by this:
![grafik](https://github.com/BadDogSkyrim/PyNifly/assets/8077005/af6e7f59-440c-400e-a44e-6c7f9e65f8f9)
Renaming these to Hinge02 etc allowed me to export the mesh.

Using Blender 4.1, and PyNifly V14.7

**Comment by BadDogSkyrim** [comment]
Fixed in next.
