### ISSUE TITLE
HKX import failed

### ISSUE THREAD

**Issue by jjtnb123** [BadDogSkyrim/PyNifly#235]
Hello，Could you please give me your Files used by your tutorial on youtube

**Comment by jjtnb123** [comment]
====================================
PYNIFLY IMPORT HKX V16.1.0


ERROR:pynifly:Import of HKX file failed
Traceback (most recent call last):
  File "C:\Users\jintai\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_scene_nifly\__init__.py", line 2814, in execute
    self.xmlfile = xmltools.XMLFile(self.filepath, self)
  File "C:\Users\jintai\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_scene_nifly\xmltools.py", line 36, in __init__
    self.open(filepath)
  File "C:\Users\jintai\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_scene_nifly\xmltools.py", line 115, in open
    fp = XMLFile.hkx_to_xml(self.hkx_filepath)
  File "C:\Users\jintai\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\io_scene_nifly\xmltools.py", line 62, in hkx_to_xml
    raise RuntimeError(f"Failed to create {xml_filepath}")
RuntimeError: Failed to create C:\Users\jintai\AppData\Local\Temp\tmp_skeleton_female.xml
INFO:pynifly:

PyNifly IMPORT of skeleton_female.hkx completed WITH ERRORS

**Comment by jjtnb123** [comment]
i don’t know how to work

**Comment by jjtnb123** [comment]
Please tell me which version you are using in  your tutorial

**Comment by jjtnb123** [comment]
i need you help please

**Comment by jjtnb123** [comment]
![image](https://github.com/user-attachments/assets/abf18cab-3722-44d3-9c4e-84b248e9d18a)

**Comment by jjtnb123** [comment]
i cant make it work

**Comment by BadDogSkyrim** [comment]
First, don't spam multiple threads. This is the right way to report an issue or problem. 

Is this animation a LE HKX file? If it's SE you have to convert using one of the HKX tools first.
