### ISSUE TITLE
OSError: exception: access violation reading 0x0000000000000000

### ISSUE THREAD

**Issue by srgraham** [BadDogSkyrim/PyNifly#63]
I'm batch importing a bunch of Skyrim SE files and I've occasionally run into this exception when processing some .nif files:
```
Import of nif failed
Traceback (most recent call last):
  File "C:\Users\scott-gig\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_nifly\__init__.py", line 895, in execute
    NifImporter.do_import(self.filepath, flags)
  File "C:\Users\scott-gig\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_nifly\__init__.py", line 853, in do_import
    imp.execute()
  File "C:\Users\scott-gig\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_nifly\__init__.py", line 814, in execute
    self.import_shape(s)
  File "C:\Users\scott-gig\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_nifly\__init__.py", line 668, in import_shape
    obj_create_material(new_object, the_shape)
  File "C:\Users\scott-gig\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_nifly\__init__.py", line 242, in obj_create_material
    import_shader_attrs(mat, bdsf, shape)
  File "C:\Users\scott-gig\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_nifly\__init__.py", line 177, in import_shader_attrs
    attrs = shape.shader_attributes
  File "C:\Users\scott-gig\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\io_scene_nifly\pynifly.py", line 940, in shader_attributes
    NifFile.nifly.getShaderAttrs(self.parent._handle, self._handle,
OSError: exception: access violation reading 0x0000000000000000
```

I'm using PyNifly V1.3 

One example .nif that does this is `meshes/clutter/woodfires/spitpotopen01.nif` from within `Skyrim Special Edition/Data/Skyrim - Meshes0.bsa`
I've uploaded it here for quicker access: [spitpotopen01.zip](https://github.com/BadDogSkyrim/PyNifly/files/7145621/spitpotopen01.zip)

Outfit Studio appears to open it without error.

I can list some more files with the same exception if it's helpful.

**Comment by BadDogSkyrim** [comment]
OK, thanks. I'll have a look and ask for more examples if needed. I won't be able to do this until week after next tho, so be patient. 

You might be able to import the nif by removing the shader node entirely in nifscope.

**Comment by BadDogSkyrim** [comment]
Problem was handling shapes that have no shader at all. Should be fixed in latest rev.
